# Project Versioning
group=com.ecommerce.catalog
version=1.0.0-SNAPSHOT

# Dependency Versions (Centralized)
tsidVersion=2.1.2
springBootVersion=3.5.3
dependencyManagementVersion=1.1.5
logstashEncoderVersion=7.4
resilience4jVersion=2.3.0
assertjVersion=3.25.3

# Muestra cada tarea en una línea propia (evita output agrupado poco claro)
org.gradle.console=plain
