# Perfil de Desarrollo Local
openapi:
  server:
    url: http://localhost:8081
  security:
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0 # 100% trazabilidad para debugging
